# ============================================================
# Name: Donnel Garner
# Date: 3/15/2026
# Class: CS432 - Web Science
# Description: Counts how many mementos (saved copies) each
#              URI has across web archives using TimeMaps
#              generated by MemGator.
# ============================================================

import os
import json
import hashlib
from collections import Counter

# Where the TimeMap files are stored
timemap_dir = "timemaps"

# The file with all our website links
uri_file = "uris.txt"

# Open the file and read every link into a list
with open(uri_file) as f:
    uris = [line.strip() for line in f if line.strip()]

# This will hold each link and how many saved copies it has
results = []

# Go through every link one by one
for uri in uris:

    # Turn the link into a unique code (used as the filename)
    hash_name = hashlib.md5(uri.encode()).hexdigest()

    # Build the path to that link's TimeMap file
    filepath = os.path.join(timemap_dir, f"{hash_name}.json")

    # Start the count at zero
    count = 0

    # If the file exists and has something in it, open it
    if os.path.exists(filepath) and os.path.getsize(filepath) > 0:
        with open(filepath) as f:
            try:
                # Read the JSON file
                data = json.load(f)

                # Mementos are stored inside data -> mementos -> list
                count = len(data.get("mementos", {}).get("list", []))

            except json.JSONDecodeError:
                # If the file is broken, just leave count as 0
                count = 0

    # Save the link and its count to our results list
    results.append((uri, count))

# Sort the list so the most archived links are at the top
results.sort(key=lambda x: -x[1])

# Show the top 5 most archived links
print("Top 5 URI-Rs by memento count:")
for uri, count in results[:5]:
    print(f"  {count:>6}  {uri}")

# ---- Now build a summary table ----

# Grab just the counts
counts = [c for _, c in results]

# Put each count into a bucket (bin)
binned = Counter()
for c in counts:
    if c == 0:
        binned["0"] += 1
    elif c <= 10:
        binned["1-10"] += 1
    elif c <= 50:
        binned["11-50"] += 1
    elif c <= 100:
        binned["51-100"] += 1
    elif c <= 500:
        binned["101-500"] += 1
    else:
        binned["501+"] += 1

# Print the final table
print("\nBinned Table:")
print(f"{'Mementos':<15} {'URI-Rs':>8}")
for label in ["0", "1-10", "11-50", "51-100", "101-500", "501+"]:
    if binned[label]:
        print(f"{label:<15} {binned[label]:>8}")